"""empty message

Revision ID: 7f8840c210fd
Revises: 
Create Date: 2020-03-02 22:13:52.533843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8840c210fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture',
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('shots_on_goal_home', sa.Integer(), nullable=True),
    sa.Column('shots_on_goal_away', sa.Integer(), nullable=True),
    sa.Column('shots_off_goal_home', sa.Integer(), nullable=True),
    sa.Column('shots_off_goal_away', sa.Integer(), nullable=True),
    sa.Column('total_shots_home', sa.Integer(), nullable=True),
    sa.Column('total_shots_away', sa.Integer(), nullable=True),
    sa.Column('blocked_shots_home', sa.Integer(), nullable=True),
    sa.Column('blocked_shots_away', sa.Integer(), nullable=True),
    sa.Column('shots_insidebox_home', sa.Integer(), nullable=True),
    sa.Column('shots_insidebox_away', sa.Integer(), nullable=True),
    sa.Column('shots_outsidebox_home', sa.Integer(), nullable=True),
    sa.Column('shots_outsidebox_away', sa.Integer(), nullable=True),
    sa.Column('fouls_home', sa.Integer(), nullable=True),
    sa.Column('fouls_away', sa.Integer(), nullable=True),
    sa.Column('corner_kicks_home', sa.Integer(), nullable=True),
    sa.Column('corner_kicks_away', sa.Integer(), nullable=True),
    sa.Column('offsides_home', sa.Integer(), nullable=True),
    sa.Column('offsides_away', sa.Integer(), nullable=True),
    sa.Column('ball_possession_home', sa.Float(), nullable=True),
    sa.Column('ball_possession_away', sa.Float(), nullable=True),
    sa.Column('yellow_cards_home', sa.Integer(), nullable=True),
    sa.Column('yellow_cards_away', sa.Integer(), nullable=True),
    sa.Column('red_cards_home', sa.Integer(), nullable=True),
    sa.Column('red_cards_away', sa.Integer(), nullable=True),
    sa.Column('goalkeeper_saves_home', sa.Integer(), nullable=True),
    sa.Column('goalkeeper_saves_away', sa.Integer(), nullable=True),
    sa.Column('total_passes_home', sa.Integer(), nullable=True),
    sa.Column('total_passes_away', sa.Integer(), nullable=True),
    sa.Column('passes_accurate_home', sa.Integer(), nullable=True),
    sa.Column('passes_accurate_away', sa.Integer(), nullable=True),
    sa.Column('passes_perc_home', sa.Float(), nullable=True),
    sa.Column('passes_perc_away', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('fixture_id')
    )
    op.create_index(op.f('ix_fixture_league_id'), 'fixture', ['league_id'], unique=False)
    op.create_table('league',
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('first_half_start', sa.BigInteger(), nullable=True),
    sa.Column('second_half_start', sa.BigInteger(), nullable=True),
    sa.Column('round', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('status_short', sa.String(length=2), nullable=True),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team', sa.String(length=128), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=128), nullable=True),
    sa.Column('halftime', sa.String(length=64), nullable=True),
    sa.Column('fulltime', sa.String(length=64), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('league_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fixture_id')
    )
    op.create_index(op.f('ix_league_league_id'), 'league', ['league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_league_id'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_fixture_league_id'), table_name='fixture')
    op.drop_table('fixture')
    # ### end Alembic commands ###
